version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    environment:
      MIX_ENV: prod
      PHX_SERVER: true

    # Expuesto solo internamente para Traefik
    expose:
      - "4000"

    volumes:
      - sqlite_data:/app/db

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.indies.rule=Host(`${PHX_HOST}`)"
      - "traefik.http.routers.indies.entrypoints=websecure"
      - "traefik.http.routers.indies.tls.certresolver=le"
      - "traefik.http.services.indies.loadbalancer.server.port=4000"

    networks:
      - traefik_proxy
      - internal

    restart: unless-stopped

networks:
  traefik_proxy:
    external: true
  internal:
    internal: true

volumes:
  sqlite_data:
